proxies:
  proxy_1:
    - ip: 181.115.168.69
    - port: 49076
  proxy_2:
    - ip: 185.21.217.20
    - port: 3128
  proxy_3:
    - ip: 103.94.7.254
    - port: 53281
  proxy_4:
    - ip: 107.191.39.172
    - port: 33765
  proxy_5:
    - ip: 52.41.192.68
    - port: 8888